---
galaxy_info:
  author: DannyRuizB
  description: Genera un panel HTML con el estado del sistema a partir de los facts
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - monitoring
    - reporting
dependencies: []
